services:
  - type: web
    name: tor-browser-service
    env: docker
    dockerfilePath: ./Dockerfile  # Adjust path if needed
    buildCommand: ""  # No build command needed for this container
    startCommand: "docker run -d -p 5800:5800 domistyle/tor-browser"
    ports:
      - 5800
